### ISSUE TITLE
The Node modules folder shouldn't be included!

### ISSUE THREAD

**Issue by khammami** [achrafbenabdalla/gitlab-kubernetes#1]
`node_modules` must not be committed in git repo. It will be generated in your CI/Docker `npm install`

To delete it from git repo:
`git rm -r node_mudules`

**Comment by achrafbenabdalla** [comment]
> `node_modules` must not be committed in git repo. It will be generated in your CI/Docker `npm install`
> 
> To delete it from git repo: `git rm -r node_mudules`

Yes m. Khalil i'll, its was just a little node js app that i created just for test i was focusing in the connection between gitlab and my kub cluster
